---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS ELB controller is a service controller for managing ELB resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon ELB
description: |-
  Manage Amazon Elastic Load Balancing (ELB) resources in AWS from within your Kubernetes cluster.


  **About Amazon ELB**


  Elastic Load Balancing automatically distributes your incoming traffic across multiple targets, such as EC2 instances, containers, and IP addresses, in one or more Availability Zones. It monitors the health of its registered targets, and routes traffic only to the healthy targets. Elastic Load Balancing scales your load balancer capacity automatically in response to changes in incoming traffic.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: Listener
  spec: '{}'
- kind: LoadBalancer
  spec: '{}'
- kind: Rule
  spec: '{}'
- kind: TargetGroup
  spec: '{}'
maintainers:
- name: "elb maintainer team"
  email: "ack-maintainers@amazon.com"
links: 
- name: Amazon ELB Developer Resources
  url: https://aws.amazon.com/elasticloadbalancing
